name: adobe_analytics
description: A new flutter plugin project.
version: 0.0.1
author: Jérémie Vincke <jeremie@movify.com>
homepage: https://github.com/vrtdev/flutter_adobe/tree/master/packages/adobe_analytics

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: be.vrt.adobe_analytics
    pluginClass: AdobeAnalyticsPlugin